[package]
name = "mojang_api"
version = "0.1.0"
authors = ["caelunshun <caelunshun@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.9", features = ["default-tls-vendored"] }
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
uuid = "0.7"
lazy_static = "1.3"
openssl = { version = "0.10", features = ["vendored"] }
num-bigint = "0.2"

[dev-dependencies]
mockito = "0.17.1"